apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: users-app
  template:
    metadata:
      labels:
        component: users-app
    spec:
      containers:
        - name: client
          image: ${K8S_DOCKER_HUB_USER_ID}/app-users
          ports:
            - containerPort: 8080
